<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $plans = [
            [
                'name' => 'Gratis',
                'slug' => 'free',
                'description' => 'Paket gratis untuk mencoba fitur dasar platform',
                'price_per_month' => 0,
                'price_per_year' => 0,
                'max_schools' => 1,
                'max_users' => 100,
                'max_students' => 100,
                'max_teachers' => 20,
                'max_parents' => 200,
                'features' => [
                    'Manajemen Siswa',
                    'Manajemen Guru',
                    'Jadwal Pelajaran',
                    'Sistem Penilaian',
                    'Laporan Akademik',
                ],
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 1,
                'has_cbt' => false,
                'has_online_course' => false,
                'has_digital_wallet' => false,
                'has_canteen' => false,
                'has_custom_domain' => false,
                'has_api_access' => false,
                'storage_gb' => 1,
                'has_email_support' => true,
                'has_priority_support' => false,
                'has_sms_notification' => false,
                'included_plugins' => [],
                'plugin_slots' => 0,
                'plugin_categories' => [],
                'bundle_savings' => 0,
                'highlight_features' => "Gratis selamanya\nCoba fitur dasar\n100 Siswa\nTanpa Plugin",
                'duration_days' => 30,
            ],
            [
                'name' => 'Starter Plus',
                'slug' => 'starter-plus',
                'description' => 'Paket dasar dengan PPDB dan Attendance otomatis terinstall',
                'price_per_month' => 750000,
                'price_per_year' => 7500000,
                'max_schools' => 1,
                'max_users' => 500,
                'max_students' => 500,
                'max_teachers' => 50,
                'max_parents' => 1000,
                'features' => [
                    'Manajemen Siswa',
                    'Manajemen Guru',
                    'Jadwal Pelajaran',
                    'Sistem Penilaian',
                    'PPDB Online (Included)',
                    'Attendance System (Included)',
                    'Support Email',
                ],
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 2,
                'has_cbt' => false,
                'has_online_course' => false,
                'has_digital_wallet' => false,
                'has_canteen' => false,
                'has_custom_domain' => false,
                'has_api_access' => false,
                'storage_gb' => 5,
                'has_email_support' => true,
                'has_priority_support' => false,
                'has_sms_notification' => false,
                'included_plugins' => ['ppdb', 'attendance'],
                'plugin_slots' => 2,
                'plugin_categories' => ['education', 'management'],
                'bundle_savings' => 400000, // PPDB 250K + Attendance 150K = 400K savings
                'highlight_features' => "500 Siswa\nPPDB Included\nAttendance Included\n2 Plugin Slots\nHemat Rp400K",
                'duration_days' => 30,
            ],
            [
                'name' => 'Professional Plus',
                'slug' => 'professional-plus',
                'description' => 'Paket profesional dengan PPDB, CBT, dan Attendance otomatis terinstall',
                'price_per_month' => 2000000,
                'price_per_year' => 20000000,
                'max_schools' => 5,
                'max_users' => 2500,
                'max_students' => 2500,
                'max_teachers' => 250,
                'max_parents' => 5000,
                'features' => [
                    'Semua Fitur Starter Plus',
                    'Keuangan Sekolah',
                    'Dashboard Analitik',
                    'Laporan Akademik',
                    'CBT Online (Included)',
                    'Priority Support',
                    'API Access',
                    'Custom Domain',
                ],
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 3,
                'has_cbt' => true,
                'has_online_course' => true,
                'has_digital_wallet' => false,
                'has_canteen' => false,
                'has_custom_domain' => true,
                'has_api_access' => true,
                'storage_gb' => 20,
                'has_email_support' => true,
                'has_priority_support' => true,
                'has_sms_notification' => false,
                'included_plugins' => ['ppdb', 'cbt', 'attendance'],
                'plugin_slots' => 5,
                'plugin_categories' => ['education', 'management', 'assessment'],
                'bundle_savings' => 550000, // PPDB 250K + CBT 150K + Attendance 150K = 550K savings
                'highlight_features' => "5 Unit Sekolah\n2.500 Siswa\n3 Plugin Included\nCBT & PPDB\nHemat Rp550K",
                'duration_days' => 30,
            ],
            [
                'name' => 'Business Complete',
                'slug' => 'business-complete',
                'description' => 'Paket bisnis lengkap dengan semua plugin otomatis terinstall',
                'price_per_month' => 4500000,
                'price_per_year' => 45000000,
                'max_schools' => 10,
                'max_users' => 10000,
                'max_students' => 10000,
                'max_teachers' => 1000,
                'max_parents' => 20000,
                'features' => [
                    'Semua Fitur Professional Plus',
                    'Wallet Digital',
                    'Kantin Digital',
                    'Payment Gateway (Included)',
                    'SMS Notification (Included)',
                    'Laporan Keuangan',
                    'Priority Support 24/7',
                ],
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 4,
                'has_cbt' => true,
                'has_online_course' => true,
                'has_digital_wallet' => true,
                'has_canteen' => true,
                'has_custom_domain' => true,
                'has_api_access' => true,
                'storage_gb' => 50,
                'has_email_support' => true,
                'has_priority_support' => true,
                'has_sms_notification' => true,
                'included_plugins' => ['ppdb', 'cbt', 'attendance', 'payment-gateway', 'sms-notification'],
                'plugin_slots' => 10,
                'plugin_categories' => ['education', 'management', 'assessment', 'finance', 'communication'],
                'bundle_savings' => 800000, // All plugins combined
                'highlight_features' => "10 Unit Sekolah\n10.000 Siswa\n5 Plugin Included\nAll Access\nHemat Rp800K",
                'duration_days' => 30,
            ],
            [
                'name' => 'Enterprise',
                'slug' => 'enterprise',
                'description' => 'Paket enterprise untuk yayasan besar dengan kebutuhan khusus',
                'price_per_month' => 0,
                'price_per_year' => 0,
                'max_schools' => 999,
                'max_users' => 999999,
                'max_students' => 999999,
                'max_teachers' => 999999,
                'max_parents' => 999999,
                'features' => [
                    'Semua Fitur Business Complete',
                    'Unlimited Sekolah',
                    'Unlimited User',
                    'Custom Integrasi',
                    'Dedicated Support',
                    'On-premise Option',
                    'White Label',
                    'SLA Guarantee',
                    'All Plugins Included',
                ],
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 5,
                'has_cbt' => true,
                'has_online_course' => true,
                'has_digital_wallet' => true,
                'has_canteen' => true,
                'has_custom_domain' => true,
                'has_api_access' => true,
                'storage_gb' => 999,
                'has_email_support' => true,
                'has_priority_support' => true,
                'has_sms_notification' => true,
                'included_plugins' => ['ppdb', 'cbt', 'attendance', 'payment-gateway', 'sms-notification'],
                'plugin_slots' => 999, // Unlimited
                'plugin_categories' => ['education', 'management', 'assessment', 'finance', 'communication'],
                'bundle_savings' => 0, // Custom pricing
                'highlight_features' => "Unlimited Semua\nCustom Integrasi\nOn-premise\nWhite Label\nAll Plugins",
                'duration_days' => 365,
            ],
        ];

        foreach ($plans as $planData) {
            Plan::updateOrCreate(
                ['slug' => $planData['slug']],
                $planData
            );
        }
    }
}
